@echo off
echo Lancement de la simulation Wokwi...
echo Attente du demarrage de MicroPython...
timeout /t 5 /nobreak

echo Upload de main.py...
python -m mpremote connect port:rfc2217://localhost:4000 fs cp main.py :main.py

echo Soft reboot...
python -m mpremote connect port:rfc2217://localhost:4000 exec "import machine; machine.reset()"

echo Pret !