services:

  postgres:
    image: postgres:15

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lamin7755
      POSTGRES_DB: futurkawa_db

    ports:
      - "5432:5432"

  mosquitto:
    image: eclipse-mosquitto

    ports:
      - "1883:1883"